### ISSUE TITLE
Improper match with PureTaboo

### ISSUE THREAD

**Issue by woodbridgesub** [PAhelper/PhoenixAdult.bundle#107]
The titles listed below are returning the exact same metadata (metadata is returned for the 19.01.03 title Eyes In the Sky). When trying to manually match, it does return results, but they are all from scenes that took place in 2019. So in the case of something from 2018, it doesn't even show up in the match results. 
One thing to note is that the example given is just one of many. Many other titles are being improperly matched and returning duplicated metadata, always with titles from 2019. Why they're matching to that specific title I don't fully understand. Hope you can help.

PureTaboo.19.01.03.Adriana.Chechik.And.Kristen.Scott.Eyes.In.The.Sky.mp4
PureTaboo.18.04.03.Kenzie.Reeves.Trailer.Park.Taboo.Part.1.mp4
PureTaboo.18.10.30.Kendra.Spade.Jekyll.And.Dad.mp4

Thanks again for your continued effort on this project.

**Comment by ColonelPud** [comment]
The agent won't be able to find "Jekyll and Dad" because PureTaboo has an issue with it. It doesn't show up in a search of the PureTaboo site under title, by date, or by cast (both male and female). Looks like they missed it in their database. Same goes for "Waking The Babysitter".

For "Trailer Park" and "Future Darkly: I found that manual update for part of title allows the agent to find the proper scene in many cases. The issue seems to be : in the title or part.

**Comment by woodbridgesub** [comment]
Appreciate the response. Could you elaborate a bit on what you mean by "the issue seems to be: in the title or part" ? Maybe there's a way to fix the incorrect duplication of metadata using an automated way rather than manually fixing each match.

**Comment by ColonelPud** [comment]
It seems like when the agent strips the : from a title, sometimes it can't be found. I found that if you use part of title "Future Darkly" and "Trailer Park" for example with the site for search, sometimes it finds them more easily.
