### ISSUE TITLE
Vixen/Blacked/Tushy studio naming

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#121]
Can you change the studio name of Vixen/Blacked/Tushy scenes from Strike 3 to their respective studio names? (Vixen/Blacked/Tushy)

**Comment by PAhelper** [comment]
Yes I can, but I don't feel it should be changed. Let's debate. The way I use sorting in Plex, I look at the "studio" as a grouping of all the sites under an umbrella site. Think of Brazzers -> Real Wife Stories, or Mofos -> ShareMyBF. In those examples Brazzers and Mofos are there "studio". In the metadata, I would set Brazzers as the Studio and "Real Wife Stories" as the Tagline. Since you can't sort/filter by Tagline, I also add a Collection named "Real Wife Stories". This way, if I want to see all the stuff made by Brazzers, I can filter my Plex library by Studio:Brazzers, then I'll get all of Real Wife Stories, along with everything else in my library made by them. If I'm only looking for RWS, I can filter by Collection:Real Wife Stories.

Similarly, I see these 5 sites (Tushy/raw, Blacked/raw, and Vixen) as a group all made by the same studio. Unfortunately, I couldn't find any official name for the group other than the director Greg Lansky. Strike 3 was the common copywrite name on all the DVD boxes, so I used that.

If I change the studio as you request, we lose the ability to see all these releases together. Actually, I guess we could filter by Director:Greg Lansky, and that would do the job. It would still break away from the formula I use to organize all other sites though...

So what do you think? I genuinely want to hear how you guys use this metadata, and why you would prefer things to be different.

**Comment by SgtBatten** [comment]
I agree with keeping it something different to the tagline. No point having a collection, tagline and studio all the same

**Comment by ColonelPud** [comment]
If only we could get the porn sites to standardize their information!!

I have my files in folders by site. When I get a file I use a bulk renamer to add the site or subsite name prefix for the specific site because I thought that was the best way to help Plex find the metadata. I also use the site listing on your page to help determine what type of search I should do if I manually input the information. In some cases that are hard to match, I go back to the original site to find the date or actress if the filename doesn't have it.

I would prefer to have the site name as studio name. No problem with using RealityKings as the studio name for all the subsites with the subsite listed in collection. For Vixen, there isn't anything to remind me of Strike 3. When I went out to see the issue, I went to the folders and collections in Plex to see the information. It wasn't obvious until I opened up several files that the studio was Strike 3. Also, there isn't any centralized Strike 3 website. Sometimes I go to the parent website trying to get a match, i.e. DDFNework for House of Taboo because sometimes I have them identified in the wrong subsite (might be my fault, but in some it is what appears on the movie.)

Overall, I really appreciate all that everyone is doing to make this system work better. Keep up the great work!! There are some of us lurkers (without programming skills) that are grateful for all you do.

**Comment by streetlurchin** [comment]
I believe the Blacked/Tushy/Vixen/Deeper _sites_ are run by a _studio_/_network_ called MadCheddar.
https://www.madcheddar.com/external.php?page=sites& 
I also label by studio/network, so Brazzers, RealityKings, Mofos, MadCheddar, Kink, FuckYouCash, Bang Bros, FullPorn, Blowpass...  And the individual sites under those umbrellas are easily sorted by collections within those...

**Comment by claygoldfinch** [comment]
I don't think Mad Cheddar is the network/studio, it appears to be related to affiliate tracking.

I'm fine with using Strike 3, though Vixen Media Group (of which Greg Lansky is the co-founder) might be a better option.
