### ISSUE TITLE
Exception when downloading metadata from DDFNetwork / PornWorld

### ISSUE THREAD

**Issue by cptn-code** [PAhelper/PhoenixAdult.bundle#1226]
The agent fails to download the metadata for a specific scene. Other scenes from the same site/network have worked flawlessly so far.

Original Filename:
hlaf.20.07.27.canela.skin.an.intimate.ass.fucking.4k.mp4
(Hot Legs and Feet)

Search Term:
DDFNetwork.20.07.27.canela.skin
PornWorld.20.07.27.canela.skin

The scene is being matched properly using both search terms.

However, the metadata is not being downloaded at all.
Looking at the log file I found an IndexError message, but I haven't been able to figure out why it does not seem to affect other scenes from the same site and how to fix it.

Log:
[log.txt](https://github.com/PAhelper/PhoenixAdult.bundle/files/6116297/log.txt)

**Comment by WolHloW** [comment]
The metadata wasn't loading because the description/summary was missing, I've submitted a fix that has yet to be merged that should resolve that issue.

For now you can match it with `hotlegsfeet.20.07.27.canela.skin`, but the scene lists no actors on its site which I've added manually in the fix I committed, once merged you should be able to match it using hlaf as in your original filename and also hotlegsandfeet (no longer hotlegsfeet).
