### ISSUE TITLE
Extra characters in PureTaboo description

### ISSUE THREAD

**Issue by ColonelPud** [PAhelper/PhoenixAdult.bundle#125]
I buy Playboy magazine for the articles :) 

PureTaboo pulls the description for the scene and that's great, however, many of the descriptions are several paragraphs long. The agent pulls the information and inserts < b r / > or < / b r > (remove spaces to view) instead of paragraph marker. Right now to clean up the description, I copy the description to notepad and replace those characters with a line break, then copy back to Plex. Is there an easier way to do that?

**Comment by ColonelPud** [comment]
Funny!! When I made the comment, the symbols were read as characters. Should have been "</br>" and "br/"

**Comment by ColonelPud** [comment]
Still not showing properly. < / b r > (remove the spaces)

**Comment by PAhelper** [comment]
Oh yeah, I can easily do that in the code. At one point I considered only keeping the first paragraph, because as you pointed out the PureTaboo descriptions are looooooooonnnggg. Would you prefer to keep the whole thing and clean it up, or just stop the description at the end of the first paragraph?

**Comment by ColonelPud** [comment]
I would prefer the whole description. Sometimes the story is almost as good as the video.

**Comment by PAhelper** [comment]
Fixed in 4aadc42
