### ISSUE TITLE
DigitalPlayground Site has changed

### ISSUE THREAD

**Issue by chempke** [PAhelper/PhoenixAdult.bundle#136]
Same problem like the Twistys one...

**Comment by SgtBatten** [comment]
Jesus why do sites change so often? They watching us? Haha

**Comment by PAhelper** [comment]
Took a quick glance. This one looks at least salvageable although the new search is decidedly worse than the previous one. And I'll probably have to drop support for full movies, as I don't find a search that returns full movie results, just the scenes. I'll see what I can come up with...

**Comment by insickin** [comment]
You cant do anything with the drop down menu? (If you search for a full movie you get a drop down menu with full movie results, separate scenes and trailers)

**Comment by Sinjin69** [comment]
Also Babes

**Comment by claygoldfinch** [comment]
Fix incoming.

**Comment by Sinjin69** [comment]
PR #225

**Comment by claygoldfinch** [comment]
Might take a little longer just due to the fact that DP includes movies. 

Each movie has its own [page/sceneID](https://www.digitalplayground.com/movie/4353789/1), but all the scenes from that movie redirect to a single [page/scene ID](https://www.digitalplayground.com/scene/4353791/1).

Will have to play around with it a bit more.

**Comment by insickin** [comment]
How is the fix going, is it coming?

**Comment by claygoldfinch** [comment]
I've actually got this about wrapped up, just have one thing left to do before I submit a PR. 

I'm currently struggling to pull the video still from the video player on movie pages. For example:
https://www.digitalplayground.com/scene/4352090/fuck-forever-trailer

Any chance you could give me a hand with this, @SgtBatten?

**Comment by claygoldfinch** [comment]
Decided to commit as-is, PR #264

**Comment by claygoldfinch** [comment]
Re-opening to address some issues I've noticed while testing.

**Comment by claygoldfinch** [comment]
I think I've got it running the best as I can with my last commit. If you're running into issues matching or pulling metadata, try rebooting Plex. If you're still running into issues, try the Plex Dance. 

Currently the agent only supports standalone scenes and full movie releases - not individual scenes from movies. I did this for several reasons:

1. The DP site only lists 4 scenes on each movie page, though many movies have more than 4 scenes. 
2. The DP site design sucks. When navigating to a page, the site occasionally refuses to load certain parts of the page. Other times, the site will just throw up a 404. Having the agent request multiple pages (which was needed to scrape the 4 listed scenes from each movie) greatly increased the probability of the site throwing up an error, and therefore the agent throwing up an error. Plex's protocol to cache each site instead of reloading each time you rematch/refresh metadata exacerbated this issue.

**Comment by insickin** [comment]
Just for information: I was tagging movies and used the site's search and came on the "trailer" page, used that scene-id and it didn't tag, searched around and found the "normal" page used that scene-id and it worked! So if your movie won't tag maybe you are trying to tag with the "trailer" id.

For example:
Digital Playground - Dangerous Women
"trailer" scene-id: [https://www.digitalplayground.com/scene/4357557/dangerous-women-trailer](url) 4357557
"normal" scene-id [https://www.digitalplayground.com/movie/4357554/dangerous-women](url) 4357554

I see that on the "trailer" page there are no actor/description info so it's only normal that you have to use the "normal" page to mine the data.

**Comment by insickin** [comment]
Just for information:

Many scenes/films have been placed twice on their website, some with the name "trailer" added on the end, others have apparently the same name... (For example [https://www.digitalplayground.com/scene/4304681/spa-seduction](url) and [https://www.digitalplayground.com/scene/4314211/spa-seduction](url) (the first page/scene-id works the 2th doesn't)) 

So if a scene/movie can't be found by the agent, try searching the scene/movie via google and try the second find!

**Comment by insickin** [comment]
I have 1 scene that has no other "pages" "DigitalPlayground - Blow Dry" [https://www.digitalplayground.com/scene/4359374/blow-dry-trailer](url) it returns: No results

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3389857/com.plexapp.agents.phoenixadult.log)

**Comment by claygoldfinch** [comment]
Pushed a bugfix on my fork that might help performance, I'll merge it in later today.

All the scenes you listed do actually work, just tested them on my setup. Again, this is just an example of how much the site sucks. Sometimes the agent is able to scrape them, other times it just won't. One place it especially seems to struggle is determining if the file is a scene or a movie. There are only two points in the site code that differentiate between them, and I have the agent checking both with my bugfix. Even so, it seems to fail pretty frequently.

**Comment by insickin** [comment]
Indeed, without updating the agent now finds the scene "DigitalPlayground - Blow Dry" perfectly...  Now I'm having trouble to get "DigitalPlayground - 50 Ways to Fuck" [https://www.digitalplayground.com/scene/4189421/trailer-for-50-ways-to-fuck](url) tagged... :man_facepalming:
