### ISSUE TITLE
Wrong Cast Photo being loaded

### ISSUE THREAD

**Issue by Leinaria** [PAhelper/PhoenixAdult.bundle#1794]
I have some videos with Rachel Rivers - https://twitter.com/RachelRiversX. However, the photo that comes up for her is of some red haired woman who looks to be in her mid 50s. I couldn't even find the woman with a google search or IMDB, so I'm not sure who she is or where her photo came from. Any way to correct that?

**Comment by Leinaria** [comment]
Okay, looks like the other Rachel Rivers is an older performer who was found on some sites, though oddly not Freeones. Some combination of removing all the sites with the wrong RR from the Order List, furious Unmatching, Refreshing Metadata, enabling Remove Obsolete Images and Remove Stored Images, and Matching again finally got the correct photo to load. 

Maybe this is just a matter of documentation so that people could resolve this themselves? I tried to look for something like that, but couldn't find any instructions for doing so, and feel like I did so partly by luck.

**Comment by diamondpete** [comment]
When I rewrote the IAFD search I had to make it so that it chooses a random image (matching priority is based on where the name matches closest to search name) from the search results. Originally it was just choosing the first result making it impossible to fix the image. There isn't much that can be done because both results are considered a good match in this case. There is no way to identify one versus the other since their names are identical. Looking at the site results I suppose it could be improved by adding a year, but that assumes IAFD is up to date.

Since its random, refreshing the metadata will allow you swap the image. You may need to refresh a couple of times to get the image you want. 

![image](https://github.com/PAhelper/PhoenixAdult.bundle/assets/87245367/1d632cf9-8014-4f8a-b676-4ae29dc65044)

**Comment by Leinaria** [comment]
So all you would need to do to swap images is to Refresh Metadata until it swaps? Would you need to do that for each piece of media, or just for one and that'll affect the others?

**Comment by diamondpete** [comment]
Once per library. The actor image is shared within the entire library.

**Comment by Leinaria** [comment]
Great, thanks! That helps a lot, should this happen again.
