### ISSUE TITLE
[bug] My Wifes Hot Friend search not working

### ISSUE THREAD

**Issue by PAHelper2** [PAhelper/PhoenixAdult.bundle#19]
Using these searches, nothing turns up:

MyWifesHotFriend - 2018-12-04 - lauren phillips
My Wifes Hot Friend - 2018-12-04 - lauren phillips

Naughty America web search can find it, if I search for "milks".  The title of the video being  "Lauren Phillips milks a big cock".   I haven't been able to get this into a search I can use the in Plex Match dialog box however.

**Comment by PAHelper2** [comment]
Interestingly, if I search for:

My wifes hot friend - 2018-05-08 - katrina jade

It works and finds that one.  Is it possible that a search for a video released yesterday just won't pop up via this search?

**Comment by PAHelper2** [comment]
If I make this code change on line 6 of siteNaughtyAmerica.py, I can get a match:

`searchString = searchString`

( This is removing: 
`+ "+in+" + PAsearchSites.getSearchSiteName(searchSiteID).replace(" ","+")` )

Testing this change in the browser, shows it working properly also:

- Doesn't work: https://tour.naughtyamerica.com/search?term=lauren+phillips+in+my+wifes+hot+friend
- Works: https://tour.naughtyamerica.com/search?term=lauren+phillips

I haven't tested this change against other Naughty America titles yet, but I'll try and update this.

**Comment by PAHelper2** [comment]
I get a match, and meta data, but I don't get a poster pulled down however.  Not sure if that's a known bug.

**Comment by PAhelper** [comment]
I've done some work to the NaughtyAmerica code, and I'm downloading this particular scene to test... Check back soon!

**Comment by PAhelper** [comment]
Alright, I'll be honest. This was some of Phoenix's original code and I have no idea why he structured the search function the way he did. After some testing, I removed the "+in+" part from that line of code you mentioned, and that seemed to straighten everything up with the search.

As for the poster art, this was a completely unrelated issue. Turns out the script stopped processing in the Actors section of the code because the link to the other actor in that scene (Alex Legend) is broken. I guess NA forgot to create the page for him. I searched the site to try and find the correct URL for the page (or specifically for photo from that page, because that's all we really care about) but couldn't find it. So instead, I wrote an exception in the code so any actors whose page is missing won't get a photo, but won't break the code from continuing either.
