### ISSUE TITLE
Continuation of project/agent

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#195]
Does anybody know where PAhelper is? Maybe I'm a little anxious but I hate to see this agent fall in disrepair/go to waste! Is he taking a break from this project or is he just on vacation or something? The last code update is from 10 day's ago and at the moment there are 3 Pull requests open. (not that PAhelper is forced or something to work constantly on this agent, I'm very happy that he has taken over from Phoenix last year and for all his hard work and praise him for it!)

I'm just noting my concern.

If he finds that he wants to stop with the development of the agent maybe he could give more people access to change/update the code
https://www.youtube.com/watch?v=61WbzS9XMwk

**Comment by SgtBatten** [comment]
I think more people having access can be a good thing rather than more forks. We already have heaps.

There's a couple guys who are regularly contributing. I'd be happy to do it also but not on my own. It didn't take me long to work out the code and how to build new sites. The more people working on it the more sights we will end up with.

**Comment by insickin** [comment]
If you indeed see how much forks there are (most of the are not maintained) it's hard to see the woods for the trees! I

 think that it's better for the agent that more people can add code to it directly so if for example PAhelper doesn't want to continue or gets sick or something the agent keeps getting updates and lives on, now only he can add updates in the (final) agent or people must start a new fork which make it unclear on which fork supports the most sites.

(Ps: I also tried to build code to support new sites but for the love of me I cant get it to work even with the support of the wiki, so I'm grateful for all of your hard work)

**Comment by dxm2891** [comment]
If you go to the Pull request you can see the people who work there. But you still have to wait for PAhelper to merge the contents. Or you can download one of the updated versions like mine and then waiting for the new version of PAhelper.

**Comment by claygoldfinch** [comment]
I agree with @insickin and @SgtBatten - optimally, this should be the main fork. Perhaps another option would be for @PAhelper to create a "nightly" branch and allow some contributors access to that?

**Comment by dxm2891** [comment]
Sorry, I hadn't read the whole post because I was in a hurry. However, I agree with the team issue. It would be advisable to create a project with several people in order to divide the work and update it more frequently. It would be better to create a post with this request and writing users who can contribute to the project.

Sorry if there are errors with the English.

**Comment by woodbridgesub** [comment]
I agree with the general idea here. I think it's best to get @PAhelper to create a nightly and allow several members to contribute and keep this agent moving forward. 

If @PAhelper is unable to continue, or simply done with this project, then let the record show that we as end users have been most impressed and very thankful for his efforts.

**Comment by insickin** [comment]
Shall we wait until the 1st of June or sooner to see if @PAhelper  returns and if he doesn't at that date someone makes a new fork with a team (more people that can edit/add site's/fix problems) behind it?

**Comment by claygoldfinch** [comment]
It has now been a full two weeks since @PAhelper has updated this repository. 

@dxm2891 and I have since merged our forks, so there is at least one repository that is fully up to date. I will continue to submit PRs to @dxm2891's repo as I make changes to my repo.

In my opinion, we should give @PAhelper a week or two more to respond. If he has not responded by then, I suggest we move all further development to @dxm2891's repo.

That said, I still believe we should have a development team in place to prevent instances such as these. @dxm2891, are you open to giving several developers access to your repo, if we do not get a response from @PAhelper in the near future? If so, we should start looking into potential users who are willing and able to. I haven't really looked into the types of permissions a repo owner can give users, but I don't think we'll need anything more advanced than approving PRs and closing Issue tickets.

@sinjin69 and @delposibl are also active developers - perhaps they'd like to chime in?

**Comment by dxm2891** [comment]
@claygoldfinch I have already entered you as a collaborator in my repository.

If there is someone else who wants to join my repository, I can add it without problem. For now I'm using the master, although I thought I would create a further branch, like a nightly

**Comment by claygoldfinch** [comment]
> 
> 
> @claygoldfinch I have already entered you as a collaborator in my repository. You should only accept the collaboration invitation.
> 
> If there is someone else who wants to join my repository, I can add it without problem. For now I'm using the master, although I thought I would create a further branch, like a nightly

Perfect, invite accepted!

Having a nightly branch is a great idea, could certainly help with weeding out the small bugs that occasionally pop up.

**Comment by insickin** [comment]
Soory to post this here but I've just updated to the latest update from @dxm2891 repository but I have a bug/question about it, I can't seem to submit a issue, where do you want me to submit my problem? (it takes ages to load search results for Girlsway scenes)

**Comment by SgtBatten** [comment]
Yes I think he deserves a little time. Sometimes life can get in the way and we don't know what is happening.

If we do move on to @dxm2891 I will happily Collab also

**Comment by PAhelper** [comment]
Hey guys, I'm not dead or gone. Just had a few things come up in life. I've been trying to keep up with the pull requests at least, if not adding my own updates...

I'm also happy to add others to the project so it can continue being managed when life gets in my way. I'll go find that button and add @dxm2891 and @SgtBatten to start, maybe a few others who've added a couple of pull requests. Sorry for the inconvenience!

**Comment by dxm2891** [comment]
No problem. You don't have to apologize if you've had your private life busy. I'm happy as others who have come back to support this project. I gladly accept the invitation. I also think @claygoldfinch  wants to help like he already did with my repository

**Comment by woodbridgesub** [comment]
@PAhelper glad you're doing ok!

I'd also like to help support this project, if you can add me

**Comment by insickin** [comment]
@PAhelper, good to have you back man!

Indeed, no need to apologize, I got a little bit nervous that it was going the same way like the original coder PhoenixPlexCode who was suddenly gone.
