### ISSUE TITLE
Naughty America not matching

### ISSUE THREAD

**Issue by pauki671** [PAhelper/PhoenixAdult.bundle#1979]
**Describe the bug**
Hi there,
I've tried a couple of naughty America sites and they are all not matching. 

**Include**
1. Scene URL  - https://www.naughtyamerica. com/scene/sexy-professor-capri-cavanni-finds-a-rocket-in-her-students-pants-and-makes-it-explode-32332
2. File Name - MyFirstSexTeacher - 24.03.08 - Capri Cavanni

The only site that seems to be working there is tonightsgirfriend, but that seems like a separate site.

**Comment by diamondpete** [comment]
The issue is that NA added an age verification landing page, so the queries are being auto redirected to the age verification page. I'll update the site list to say direct id only until someone comes up with a fix (I tried but I'm have trouble getting it to not auto redirect).

The Naughty America scraper will auto ignore text if you include a scene id so naughtyamerica.32656.jesse.pony.neighboraffair should work as well.

**Comment by diamondpete** [comment]
> The issue is that NA added an age verification landing page, so the queries are being auto redirected to the age verification page. I'll update the site list to say scene id only until someone comes up with a fix (I tried but I'm have trouble getting it to not auto redirect).

Never mind, I figured it out. I have a fix soon.

**Comment by WhiteRusHub** [comment]
I think I never had a problem with the age verification because I run my pc with a vpn. Apparently these other countries don't require the same age verification. 
    On Saturday, November 23, 2024 at 01:17:21 p.m. EST, diamondpete ***@***.***> wrote:  
 
 



The issue is that NA added an age verification landing page, so the queries are being auto redirected to the age verification page. I'll update the site list to say scene id only until someone comes up with a fix (I tried but I'm have trouble getting it to not auto redirect).


Never mind, I figured it out. I have a fix soon.
