### ISSUE TITLE
Kink.com New and Missing Channels

### ISSUE THREAD

**Issue by yes12397** [PAhelper/PhoenixAdult.bundle#210]
below is the list of Kink.com for other and New Channels which are not not Listed in PA. 
if Someone can add that would be grateful.

**BDSM**

- Amator
- Ball Gaggers
- Bizarre Video
- Bleu Films
- Hogtied Up
- Infernal Restraints
- Proud and Perverted
- Severe Sex Films
- Struggling Babes
- Wasteland

**Hardcore**

- Animated Kink
- Deviant Hardcore
- Digital Sin
- Evolved Fights
- FetishNetwork
- Fucked and Bound
- Harmony Fetish
- Pascals Sub Sluts
- Pornstar Platinum
- Sexual Disgrace
- Sexually Broken
- Spizoo

**Femdom**

- Banana Jacks
- Bound Men Wanked
- CFNMEU
- Captive Male
- Carmen Rivera
- FemDum
- Femme Fatale Films
- Lakeview Entertainment
- Medical y Sado
- Plumperd
- Revenge Of The Baroness
- Strapon Squad
- Submissive X
- The Venus Girls

**Fetish**

- Fembot Academy
- Filth Syndicate
- Machine Dom

**Gay**

- Alternadudes
- Bonus Hole Boys
- Bound And Gagged
- Boynapped
- Ducati Porn
- FetishNetwork Male
- Fight & Fuck
- Gentlemens Closet
- My Friends' Feet
- Nasty Daddy
- SW Nude
- Str8Hell
- Yesirboys

**Comment by claygoldfinch** [comment]
I think the reason why many of these weren't added is because they're not actually Kink.com subsites/channels.

Some quick examples:

- Digital Sin - Part of the New Sensations network
- Deviant Hardcore
- Sexually Broken - Part of the Intersec network
- Spizoo

**Comment by yes12397** [comment]
true but they show in kink search. but it doesnt harm to add them all and they will show in  kink search. and most of these subsites are not up to date . example ; a video of Spizoo in kink will show release date 2019 while if you went to Spizoo main page u will find it 2017 or 2018 video . its not about to have a duplication of site search . objective is to have kink with all subchanneles available in search to fill missing metadata.

**Comment by claygoldfinch** [comment]
While I agree that the ultimate objective of the client is to pull metadata for as many sites/studios as possible, I think that adding support for all the sites/studios Kink offers would only complicate the client and user experience, due to a few reasons:

-  Kink has far from a comprehensive library for most studios. Great example would be the Intersec Network, where Kink only offers ~20 videos from their collection (of hundreds).
-  Like you stated, Kink has altered most, if not all of the scenes titles and dates to be significantly different from that of the original site.

That said, I don't have any issue adding support for studios with a comprehensive and accurate library. A great example would be Twisted Factory (Chantas Bitches, Fucked and Bound, Captive Male), which Kink bought out and is now the main and only distributor.

Anyone else have any input?

**Comment by claygoldfinch** [comment]
All Twisted Factory channels now supported (PR #225).
