### ISSUE TITLE
sometimes pervmom pulling wrong metadata even when the name appear correct with exact match

### ISSUE THREAD

**Issue by xmxier** [PAhelper/PhoenixAdult.bundle#222]
sometimes pervmom pulling wrong metadata even when the name appear correct with exact match?

**Comment by claygoldfinch** [comment]
Have any examples? Search term & log file?

**Comment by xmxier** [comment]
just now tried to match /899/welcum-home-stepmom/aaliyah-love2
it ends up matching Unclasp Her Stepmom Cooch with different pictures for the scene and the actress.

**Comment by xmxier** [comment]
and every time I try to refresh metadata it ends up with new wrong thumbnail.

**Comment by claygoldfinch** [comment]
Thanks!

This was caused by a commit I made a couple weeks back (1b32c15), sorry bout that. Should be totally resolved in PR #219. PR also fixes an issue with the actress for that scene. Let me know if you run into any other issues with scenes/actresses, I don't have a large PervMom collection to test with.
