### ISSUE TITLE
a litte help please

### ISSUE THREAD

**Issue by ferengi82** [PAhelper/PhoenixAdult.bundle#229]
hi,

i tried to add my first Site (first time on git, python beginner, so please be patient)

Title, Description and some Pictures are working, but i cant get the Date right. (The Xpath works if i try it in an Browser or in an python-script)

Would be nice if someone could give me a hint what im doing wrong, Thanks!

here is the code:
https://github.com/ferengi82/PhoenixAdult.bundle/commit/1a4674d262158dc2bb26a3634687beeee0aeba9c

**Comment by claygoldfinch** [comment]
Date scraping is working just fine for me in the newer scenes, such [as this one](https://www.littlecaprice-dreams.com/project/trailer-thats-me-little-caprice/#). 

Older scenes (such as [this one](https://www.littlecaprice-dreams.com/fan-meeting-in-rouen/)) seem to have a very different page layout - this may be where you're running into issues?

Just a heads up, line 9 should be this:

`for searchResult in searchResults.xpath('//div[@id="left-area"]/article'):`

Otherwise you'll only get the first search result.

**Comment by ferengi82** [comment]
tanks for the quick answer.
I forgot to restart plex after editig the init file.

Created my first Pull request, hoping everyting is ok.
