### ISSUE TITLE
Naughty America (My First Sex Teacher) Tagging

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#31]
I am having trouble with tagging: https://tour.naughtyamerica.com/scene/teacher-brandi-love-really-caresif-you-have-a-big-dick-24593?nats=4.10025.8.8.1169.0.0.0.0 

Can someone tell me with what combination I can get this scene tagged?

**Comment by PAhelper** [comment]
Downloading this scene to test...

**Comment by PAhelper** [comment]
@insickin My source for getting this scene is a little slow, but I made a code change on another issue that may have resolved this one. Can you test again, see if it acts any better?

**Comment by PAhelper** [comment]
After the changes I made, I had a hard time getting it to NOT match:
My First Sex Teacher - Brandi Love Bambino
My First Sex Teacher - Brandi Love (gives a list, but the correct scene is in the list)
My First Sex Teacher - 2018-09-13 (gives a list, but the correct scene is in the list)
myfirstsexteacher - teacher brandi really

Let me know if you're still having trouble with this one, otherwise we'll close it out...

**Comment by insickin** [comment]
Ok, updated but it won't find anything anymore....

**Comment by PAhelper** [comment]
How about now?
