### ISSUE TITLE
Custom Actress Override on Plug-in Update

### ISSUE THREAD

**Issue by josst10** [PAhelper/PhoenixAdult.bundle#332]
Could the PAactors.py file be changed to pull in custom info from another python file locally that users can update with our own custom changes and that file not be updated? 

For instance, I can append this to the end of the file (PAactors.py) and it works great but on a plug-in update, it gets overwritten (obvi).

        if metadata.studio == "insert studio name like f**kedhard18":
            if newActor == "Alexis":
                newActor = "Alexis Adams"

Ideas?

Thanks!

**Comment by SgtBatten** [comment]
Crete a pull request with all your changes and we can add it to the permanent file. That is kinda what we're doing here. Collectively creating this agent

**Comment by josst10** [comment]
Thanks man. So what is the standard we're using. Apologies if I am asking something already discussed.

**Comment by SgtBatten** [comment]
What you want to achieve is to standardise the names so that if a site uses an abbreviated name, or first name only, we change it to the full name so it matches all the other sites.

Your example seems good

**Comment by claygoldfinch** [comment]
@josst10 www.indexxx.com is a good place to check for standardized names.

**Comment by josst10** [comment]
Is that the agreed upon standard? I know this is minor but it would be helpful to understand a little better. For instance, in PAactors.py, under the blanket name change

"##### Replace by actor name; for actors that have different aliases in the industry"

we have;             

```
if newActor == "Anjelica" or newActor == "Ebbi" or newActor == "Abby H" or newActor == "Katherine A":
                newActor = "Krystal Boyd"
```
But then under X-Art, we have;

```
if newActor == "Angelica":
               newActor = "Anjelica"
```
Indexxx shows Anjelica and IAFD shows Abbie but I think the most definitive is Krystal Boyd. 

Just throwing it out there!

**Comment by claygoldfinch** [comment]
I generally prefer indexxx due to the way they organize their site. When you go to an actresses page, you can very easily see what their name was not only on particular sites, but also on the subsites of each site. Also, you can see how many scenes each actress participated in for each site/subsite.

If you visit the profile for a site/subsite, you can quickly identify many of the actresses that have shot for that site, and the name they shot under - this makes it very simple to add to PAactors after you've added support for a site to the client.

That said, quite a few people have edited this file, so there isn't a "real" standard.

Re: Anjelica - According to indexxx, she's only performed under the name of Krystal Boyd for 3 scenes out of the hundreds she's in.
