### ISSUE TITLE
VPN Cause Issues?

### ISSUE THREAD

**Issue by dkmontague** [PAhelper/PhoenixAdult.bundle#342]
Wondering if using a VPN can cause issues here.  I installed per your instructions on Windows 10 but no results are being returned. Strangely, yesterday it was working for a short while.  Do you have any troubleshooting tips?

**Comment by claygoldfinch** [comment]
Log?

Here's the only issue I've seen regarding VPNs:
https://github.com/PAhelper/PhoenixAdult.bundle/issues/308

**Comment by dkmontague** [comment]
[com.plexapp.agents.localmedia.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3479879/com.plexapp.agents.localmedia.log)

**Comment by dkmontague** [comment]
[com.plexapp.system.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3479901/com.plexapp.system.log)

**Comment by dkmontague** [comment]
[com.plexapp.agents.localmedia.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3480429/com.plexapp.agents.localmedia.log)

I made sure the files were named appropriately.  Example: Blacked - 2014-12-31 - Actress

**Comment by claygoldfinch** [comment]
Unfortunately the localmedia log doesn't tell us too much - you'll have the grab the PhoenixAdult log. Should be available at:
```%LOCALAPPDATA%\Plex Media Server\Logs\PMS Plugin Logs\com.plexapp.agents.phoenixadult.txt```

**Comment by dkmontague** [comment]
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3484122/com.plexapp.agents.phoenixadult.log)

Sorry about that!  Here is the correct log file.  It worked today when re-adding so I think it is OK as far as connectivity.  It may have been too many queries in short amount of time.  

An unrelated thing I noticed, however, was that only 330/350 movies were loaded correctly.  It seems like it is incorrectly labeling some files as duplicates by not considering the dates and only looking at the actress.

**Comment by claygoldfinch** [comment]
Most of these seem related to issues with the Strike3 Network (Blacked, Tushy, etc). Those should all be resolved with my latest PR.

Do you have any specific examples of files that were labeled as duplicates?

**Comment by dkmontague** [comment]
I redid it last night and had the same issues but ended up just "splitting apart" the duplicates in Plex and unmatching so I have a list.  When trying to manually match them, the appropriate scenes dont come up in the list.  

![image](https://user-images.githubusercontent.com/23252487/62838477-91f9d700-bc31-11e9-94fd-669661d5b28a.png)

**Comment by claygoldfinch** [comment]
Best option here would be to change your search terms - try title search rather than actor search. or title search in combination with actor search. The agent uses Blacked's search function, so if that fails to find the correct scene then the agent will also fail to find the correct scene.

For example:

**Search Term:** Blacked - 2019-03-16 - Marley Brinx
The agent requests this site:
https://www.blacked.com/search?q=marley%20brinx
Which doesn't have the correct scene on it.

vs 

**Search Term:** Blacked - 2019-03-16 - Share Me
The agent requests this site:
https://www.blacked.com/search?q=share%20me
Which does have the correct scene on it.

or 

**Search Term:** Blacked - 2019-03-16 - Marley Brinx Share Me
The agent requests this site:
https://www.blacked.com/search?q=marley%20brinx%20share%20me
Which does have the correct scene on it.
