### ISSUE TITLE
Folder Structure Question

### ISSUE THREAD

**Issue by PAQuestions** [PAhelper/PhoenixAdult.bundle#371]
Not really an issue, at least I don't think it is. But hopefully someone can help me.

How do you guys organize your folder structure? I recently added the date into my file names, and now the information doesn't seem to be getting pulled at all.

My file structure is like this. Adult/TeamSkeet Network/My Babysitters Club/My Babysitters Club 2016-09-17 Caught Red Pantied.mkv

When I refresh my library all that shows up for the titles are "My Babysitters Club". In the logs it looks like nothing is being used as the search query.

When I have the structure like this. Adult/My Babysitters Club 2016-09-17 Caught Red Pantied.mkv
The correct information will be pulled.

Is this a problem with the scanner or is it my folder structure? Any help would be appreciated.
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3512451/com.plexapp.agents.phoenixadult.log)

**Comment by SgtBatten** [comment]
Plex does this weird thing where it searches for the folder name if there is only one file (or the first file in that folder)

That log shows it searching for just the site name. 

If you manually match that one any subsequent ones added to the folder will be fine.

**Comment by PAQuestions** [comment]
Any chance you have any other solutions? This doesn't seem to be working for me.

**Comment by SgtBatten** [comment]
Please share a log of a manual match failing

**Comment by josst10** [comment]
I'll just throw out there how I organize mine if anyone is curious. I always keep the folder that directly has the .mp4 file as original as possible. For instance, say a site like Babes that needs to be changed to a scene name. I would have Adult/Babes/babes.xx.xx.xx.actressname.scenename (if included).mp4. I never change that folder name because then I can always change the .mp4 back to the original in seconds using Advanced Renamer. It works for me and allows me to test things pretty well too knowing I can always revert back and start over. Just thought I would throw that out there.

**Comment by josst10** [comment]
I'll just throw out there how I organize mine if anyone is curious. I always keep the folder that directly has the .mp4 file as original as possible. For instance, say a site like Babes that needs to be changed to a scene name. I would have Adult/Babes/babes.xx.xx.xx.actressname.scenename (if included)/babes - scene name.mp4. I never change that folder name because then I can always change the .mp4 back to the original in seconds using Advanced Renamer. It works for me and allows me to test things pretty well too knowing I can always revert back and start over. Just thought I would throw that out there.

**Comment by PAQuestions** [comment]
Manual matching does work, but when I add more content into that folder the problem persists on those new files.

I've tried having all the files in the folder when I manually match and tried moving them after. Neither seem to work.

**Comment by SgtBatten** [comment]
Interesting. I use a similar structure to you @PAQuestions  without issues.

xxx/studio/subsite/subsite - sceneID - Scene title (date).mp4

**Comment by PAQuestions** [comment]
I recreated my library from scratch and it seems to be working smoothly now. Thanks for the help!
