### ISSUE TITLE
No search results for Lubed.com releases

### ISSUE THREAD

**Issue by alexholliz** [PAhelper/PhoenixAdult.bundle#38]
This might be me not correctly formatting my titles for searches, but I can't make any of the lubed titles show up in plex. I took a look at the way the title search breaks things down, but I can't make this video file work, for example: "Lubed: Wet & Wild Besties".

On the Lubed.com website, the title following the lubed URL is "wet-wild-besties" and I have tried searching with the Name set to "Wet Wild Besties", "Lubed - Wet Wild Besties", "Lubed - Wet & Wild Besties", and just "Lubed" and gotten no results every time.

**Comment by PAhelper** [comment]
No, I think you're doing it exactly right. The problem is that Plex is built with an older version of certain libraries that don't play nice with modern SSL handshake requests. I'm pretty sure Lubed is one of the sites that's being affected by this right now (see the other topic on LesbianX for more details). I think I can solve this by changing the plugin code to use modern libraries, but unfortunately none of the image functions will work for these sites using SSLv3, so no posters, no background art, no actor photos. Hopefully I can at least get search results and metadata working though...

**Comment by alexholliz** [comment]
Closing this then, because it's a duplicate. I'll poke around and maybe do a PR if I can find anything useful.
