### ISSUE TITLE
julesjordan combine multiple scenes into one !!

### ISSUE THREAD

**Issue by mukalaaa** [PAhelper/PhoenixAdult.bundle#507]
Hello and great job for the awesome plugin 

I have come across a strange problem when organizing my JulesJordan library...after following proper naming structure... all videos were tagged properly except for few that plex combined together as duplicates of the same video and that is not the case... they are different clips!

For example:
I clicked on the media info for one of those and here are the details:
Z:\JulesJordan - 13-05-28 - Kiara Mia Big Tits Smothers Lexington Steele.mp4
Z:\JulesJordan - 18-12-24 - Canela Skin Hot Latina Gets Maximum Penetration In Her ASS!.mp4
Z:\JulesJordan - 19-03-29 - Big tit MILF Ava Addams is a Bra Buster!.mp4
Z:\JulesJordan - 19-04-23 - Lela Star tits and ass on South Beach!.mp4

as you can see the clips are different but Plex marked them all as duplicates... Am I missing something here?

**Comment by mukalaaa** [comment]
Ok so I deleted the library and I only added 51 JulesJordan clips. out of those 51 clips. Plex is showing only 25 and is marking the rest as duplicates... some movies have 13 duplicate badges on the top right corner!!

I guess maybe JulesJordan is broken !!

**Comment by HWatBobby** [comment]
Searching all those scenes on Jules Jordan brings up the same scene first in the search results: Butt Slut Nelly Kent Gets An Anal Lesson. Its showing that scene first for a bunch of sites.

Whoever can fix this, it's possible using the advanced search string (http://www.julesjordan.com/trial/search.php?st=advanced&qall=) instead of what is listed in PASearchSites.py (https://www.julesjordan.com/trial/search.php?query=) would fix that issue because only the scene requested is given.

**Comment by mukalaaa** [comment]
I wish I know how to fix this... but my coding experience is zero. although I am willing to learn if pointed in the right direction to help with the amazing plugin. 

it became like the goto plugin for many many Reddit users. 

Also, @HWatBobby , Thanks for the replay so you do see the problem just like me... I thought I was doing something wrong !!

**Comment by HWatBobby** [comment]
I didn't have a JJ scene to test this so I went and got the Lela Star one you mentioned and did see the scene mismatch issue. I can confirm changing the search string does fix the issue.

If you want a quick fix you can find your PASearchSites.py file and edit it in Notepad or Notepad++. Search for Jules Jordan and in the string that shows

`https://www.julesjordan.com/trial/search.php?query=`

change it to

`http://www.julesjordan.com/trial/search.php?st=advanced&qall=`

You can find the PASearchSites.py file under %LOCALAPPDATA%\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code on Windows or \appdata\[plex]\Library\Application Support\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code if you use Unraid.

I would recommend backing up the file first so you can revert if needed.

**Comment by mukalaaa** [comment]
Ok, You sir are a magician !! That worked 100% 
Now, just so I can learn this stuff in order to help myself and others, May I know how did you know changing the string will fix the problem? 
Also, How did you know that "search.php?st=advanced&qall=" is the proper string to be used?

**Comment by HWatBobby** [comment]
I searched for the scenes you provided and noticed the same scene was coming up in the results, so I checked the PASearchSites file and saw the basic search string being used.

After seeing the same scene coming up I figured there had to be an issue with JJ's basic search function. Then I noticed there was an advanced search function on the site and gave that a try and the scene I searched for came up.

Did some more testing with the advanced search string because if you do an actual advanced search the web address looks like this:

`http://www.julesjordan.com/trial/search.php?st=advanced&qall=Lela+Star+tits+and+ass+on+South+Beach&qany=&qex=&none=&tadded=0&cat%5B%5D=`

So I tested if it would work by removing `&qany=&qex=&none=&tadded=0&cat%5B%5D=` and just going to `http://www.julesjordan.com/trial/search.php?st=advanced&qall=Lela+Star+tits+and+ass+on+South+Beach` and it worked.

Just a bunch of trial and error. I always look up the scene and check PASearchSites, though. I know very little about coding, but I've been going through those code files and looking at the wiki and it's helped a lot.

**Comment by mukalaaa** [comment]
Thank you so much... Your amazing personality in actually wanting to help others like me learn is outstanding. 

Thank you so much again

**Comment by HWatBobby** [comment]
No problem. The more people we got looking at this stuff and figuring it out the easier it is for Sgt and Clay to implement the fixes into the code.

**Comment by mukalaaa** [comment]
Do you think I can use the same technique to fix Twistys?

I looked in the code and the string was "https://www.twistys.com/scene/" 
I go to the website and I search for "Tailored to Perfection" by selecting search scene first and it comes up fine... but for some reason, the plugin has difficulties pulling any metadata !!

**Comment by HWatBobby** [comment]
For those sites, there were some changes in the background. I've seen it on Mofos sites which uses the same layouts. I was able to fix my Mofos issue. I'll look into Twistys and the other similar layout sites later.
