### ISSUE TITLE
Joymii support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#65]
I'm tagging my Joymii scenes, a few scenes are not correctly tagged/missing Poster/Background/cast/wrong scene name:
Joymii - before sunset [https://joymii.com/site/set-video/code/rbv239](url)
Joymii - Young & Perfect [https://joymii.com/site/set-video/code/zcc622](url)
Joymii - Wanna Be Watched [https://joymii.com/site/set-video/code/uxi285](url)
Joymii - Warm, Hot, She [https://joymii.com/site/set-video/code/ouk868](url)
Joymii - Wet Dreams [https://joymii.com/site/set-video/code/mcv663](url)

**Comment by PAhelper** [comment]
I only had 1 Joymii scene in my collection. I checked my tracker and none of these particular scenes were listed, but I did download a few more Joymii scenes to test with.

**Comment by PAhelper** [comment]
Try the latest code.

**Comment by ColonelPud** [comment]
I originally posted this on the Plex Forums. I was hoping you could help me
understand the best way to set up the files:

I’m a new user. I have Plex installed on Synology NAS and have uploaded
adult movies and videos to the NAS. In the libraries I originally had adult
movies in a “movie” library-type folder and videos in a “other videos”
library-type folder. I had website folders and subfolders for the different
areas. The file naming convention was “title - actor” within the website
subfolders. It appears the best way to organize the adult scene videos is
to use "movie" library rather than "other video" and move all the titles
into one folder and rename all the titles with “site - title” or “site -
date- actor” if no title is available in one folder and let the agent parse
the subfolders as collections. I have software to quickly rename groups and
can add the site name and remove the actor information from my current
titles. What is the best way to organize the files to support the agent.
Also, if I remove the actors from the title and the file isn’t found, how
can I preserve the actor information I have manually collected for files
that aren't found. Thanks in advance.

**Comment by insickin** [comment]
> 
> 
> Try the latest code.

Thanks that did the trick! 

I have 1 problem left, it seems that the cast doesn't seem to be correct on some scenes for example: Joymii - before sunset https://joymii.com/site/set-video/code/rbv239 gives Den (blank photo) and Connie Carter as the cast but the real cast is: Den and Josephine can you take a look at it and fix it?

**Comment by PAhelper** [comment]
Oh, I'm 90% sure that's because the actress normally goes by "Connie Carter", but on Joymii she's listed as "Josephine". The name gets replaced in PAactors. I had the same thing happen to me with some of my Joymii scenes. The actress we usually know as "Gina Gerson" (aka Doris Ivy) is listed as "Gina G." on Joymii. It was caught by the code in PAactors and replaced to her more commonly used named of "Gina Gerson"...

If Joymii/Josephine and Connie Carter are not the same girl, let me know and we can fix this...

**Comment by insickin** [comment]
All scenes that include Ariel can't be found/tagged, after looking into it it seems that all scenes including her are marked on the Joymii site as Photo sets, can you work around this or is this a limitation?

**Comment by PAhelper** [comment]
Looks like the photo pages have just as much info as the video pages, so they could be included in search results. I've made the code change. Hopefully there aren't many Photo Sets listed on the site that don't have video, because then we're just muddying up the search results with false hope for scenes that don't exist.

**Comment by insickin** [comment]
Oke, the scenes of Ariel are now (half) recognized, it scrapes no Background/Poster and other info and the scenes are tagged as "Red Hot Ariel [Joymii] 2012-11-14" can you look at it?

**Comment by PAhelper** [comment]
Yep. I made a few code changes that should allow Joymii Photo Set info pages to be used as valid results now.

**Comment by insickin** [comment]
Now i'm only missing the actors and the title is messed up, like: "Super Toy [Joymii] 2012-12-02" instead of "Super Toy"

**Comment by PAhelper** [comment]
Pretty sure I got this sorted out. My tracker doesn't have these particular scenes available, but I downloaded the oldest Joymii scenes I could find and made a point to match the photo results, and mine are all working now. Please try again.

**Comment by insickin** [comment]
Thanks, now it works flawless! (only 1 problem with the photo's of the actors, see: [https://github.com/PAhelper/PhoenixAdult.bundle/issues/71](url) )

**Comment by PAhelper** [comment]
Good deal. I'm going to close this issue out then. The actress matching will be addressed in the other issue.
