### ISSUE TITLE
EvolvedFights no matching

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#843]
www.evolvedfights.com no matching directly by Title, sceneID or actress name.

**Comment by DirtyRacer1337** [comment]
logs

**Comment by PowerModder** [comment]
Hello! Kink is providing evolved fights (both versions) scenes at 'slower pace' from the 'default' sites so only a few scenes can be matched. I matched them using a media Title: SiteName - SceneID - Whatever...
If I have time i will make another .py to take data from those sites and not Kink. It will require to have exact title as shown at the URL of evolvedfights site (example of the required media Title: SiteName - Actor1 vs Actor2). Also, this site doesn't provide much metadata for posters/background that's why when I added support I chose just to add them from Kink file.
I just want to ask if it is ok to pull them at the repo when they are already being supported by another 'method'.

**Comment by DirtyRacer1337** [comment]
@PowerModder if you gonna be doing it, check `siteSexLikeReal.py`, it's helps you make searching through Google

**Comment by drraymond27** [comment]
I think is better from the evolvedfights.com site, because in Kink.com only have a few scenes, and many no matching for that.

**Comment by PowerModder** [comment]
I don't have that much knowledge @DirtyRacer1337 :D . I will try to use it as a template but at my mind it will be much easier just to use the Title and maybe Date from the site.
I will give it a try soon...

**Comment by drraymond27** [comment]
Hello, this issue is already fixed?

**Comment by PowerModder** [comment]
I just added a pull request
