### ISSUE TITLE
Question about Match Score

### ISSUE THREAD

**Issue by woodbridgesub** [PAhelper/PhoenixAdult.bundle#94]
I have several titles that I have listed below which do not properly match. When I manually match the title, the first (and sometimes only) item that it finds is the correct item, but always with a Score of 75 or less. My question is: is there a Score 'cutoff' that permits an automatic match but prevents matching for anything lower than 75, allowing the user to make the match it manually? If there is no such cutoff, do you have any ideas why something like the Babes title below finds only one match (the correct one) when done manually but doesn't automatically match to that item on its own?

Here are 3 titles that are doing as described above:
Babes.18.08.22.Ella.Knox.Break.Of.Dawn.mp4
interracialblowbang.18.11.15.marica.hase.mp4
interracialpickups.18.11.13.melody.parker.mp4

**Comment by insickin** [comment]
I think that you need to rename you'r files so that Plex/the agent can more easily recognize them.
For example the Babes scene:
Babes - Break Of Dawn.mp4
or
Babes - 2641584

You will see that Plex/the agent more easily recognizes the scenes that way.

**Comment by woodbridgesub** [comment]
@insickin I appreciate the reply. Renaming files is one option, but for those with a large amount of media, the whole purpose of a plugin such as this is to minimize that effort. Additionally, I'm following the naming convention as given in the readme file:
Site - YYYY-MM-DD - Porn Star Names.[ext]

So the question still remains whether there is some sort of cutoff for score. If not, then what's preventing the match.

**Comment by insickin** [comment]
Just to be clear, in the example you say that your filenames are with dots and in the readme file they are without dots, maybe it makes a difference?...
> Site - YYYY-MM-DD - Porn Star Names.[ext]

**Comment by woodbridgesub** [comment]
> Just to be clear, in the example you say that your filenames are with dots and in the readme file they are without dots, maybe it makes a difference?...

Actually, no. As per the documentation, "periods and dashes are replaced with a single space." 

I did actually solve the issue though, it seems that when parsing the file name, specifically for Babes, the search function will not work when the actor name is combined with the scene name.

I'm still not sure about the other 2 titles I listed in my first post, but I'm sure it's just a matter of time.

Appreciate the help @insickin !

Now I'm just waiting for PAHelper to give this a quick read and just let us know if there is some sort of cutoff.

**Comment by PAhelper** [comment]
I gotta be honest: I don't know how Plex chooses to auto-match a file or not. My guess is the same as yours: if a match scores above a certain percent, it will auto-match. If not, it will just import the file without matching it automatically. I manually match probably 75% of my downloads, because I don't rename the files at all. Often the files I download aren't named in a way that this agent likes, so I just manually Match them in Plex and then it's done.

I can tell you how the file is scored, because that happens in the programming. First, a little background on what happens to your filename when matching begins:
It starts with the filename minus the extension. I'll use one of my recent downloads as an example...
`ManuelFerrara.19.02.06.Eliza.Ibarra.Is.A.Pretty.Little.Slut.XXX.1080p.MP4-KTR`

Next it strips out a bunch of characters or phrases:
" : ! [ ] ( ) & RARBG 1080p 720p XXX MP4-KTR
So my example would now look like this:
`ManuelFerrara.19.02.06.Eliza.Ibarra.Is.A.Pretty.Little.Slut`

Next it replaces periods and dashes with spaces:
`ManuelFerrara 19 02 06 Eliza Ibarra Is A Pretty Little Slut`

Next section I'm still working out details, but it will go through a process to look for common site abbreviations, such as "bblib" is Brazzers' "Big Butts Like It Big", or "fho" is "Fakehub Originals", etc. This section doesn't apply to my example, but it basically searches for "bblib" and replaces it with "Big Butts Like it Big" in the search input before moving on...

Next it will try to match to a site in the big site list. It loops through each siteName of each supported site. This part does not alter the search variable, only returns the site number that matched.

If a site was matched in the previous step, it tries to strip it out of the file name:
`19 02 06 Eliza Ibarra Is A Pretty Little Slut`

Next is a special bit of processing for Babes network searches, where it strips out any word that contains an apostrophe. This is because the Babes search function (on THEIR site) doesn't handle apostrophes at all. I tried omitting them, I tried replacing them with another character like a dash or space, I tried encoding the apostrophe and just cannot return any results as long as that word is included. Note this section ONLY applies to Babes network, no other network is affected.

Finally, it checks to see if a date is left at the beginning of the search string with either 2-digit year or 4-digit year. It saves that date off to another variable, then removes it from the search string:
`Eliza Ibarra Is A Pretty Little Slut`

Now, why is that important to the score? If the filename (or manually entered search terms) included a release date which the code can recognize and pull out as in the example above, the SCORE will be based on the release date. If the release date is not included in the search terms, or if the site's search feature doesn't return a release date, then a plain text comparison of your search string against the search result's title is used.

**Comment by PAhelper** [comment]
The actual scoring mechanism, whether using Date or String comparison, work the same.

Score = 100 - (calculation of how different they are)

If you compare "apples" to "apples", there is a difference of 0, so Score = 100 - 0 = 100
If you compare "Apples" to "apples", there is a difference of 1, so Score = 100 - 1 = 99 
If you compare "Apples" to "oranges", there is a difference of 23, so Score = 100 - 23 = 77

I started adding a third scoring mechanism to one of the networks, Mofos maybe? It would compare the subChannel you passed through the search (well the siteName really) against the subSite in the search result. If they were the same, it wouldn't lower your score any, but if they were different it would knock the score down a little. I didn't carry that idea over to any other networks though, because it gets tricky if you pass "lEtsTrYaNaL" but the search result says it should be "Let's Try Anal", it'll match fine for finding the result, but would destroy the score even when it found the right scene.

**Comment by woodbridgesub** [comment]
Appreciate the detailed explanation!
