### ISSUE TITLE
NubilesFilms is not pulling metadata

### ISSUE THREAD

**Issue by justmultiplex** [PAhelper/PhoenixAdult.bundle#974]
NubilesFilms is not pulling metadata. The match works perfectly, the title and date in the search/match is shown correct, but no metadata is fetched.

I checked the XPATH (metadata.title = detailsPageElements.xpath('//div[contains(@class, "content-pane-title")]//h2')[0].text_content().strip()) as it was explained in another thread and it seems to work fine and show the correct title (I'm not a coder).

File/Scene: Nubile Films - 20-06-23 - Game On

```
CRITICAL (agentkit:1095) - Exception in the update function of agent named 'PhoenixAdult', called with guid 'com.plexapp.agents.phoenixadult://7TReA9V|525?lang=en' (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b23ab3896/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1093, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 1501, in update
    metadata = PAsearchSites.siteAussieAss.update(metadata, siteID, movieGenres, movieActors)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/networkNubiles.py", line 49, in update
    metadata.title = detailsPageElements.xpath('//div[contains(@class, "content-pane-title")]//h2')[0].text_content().strip()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b23ab3896/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range
```

**Comment by PowerModder** [comment]
In case you are wondering...The problem was not at the xpath but what is being requested.
With your Scene Title:  Nubile Films - 20-06-23 - Game On we have a request...
INFO (logkit:16) - Requesting GET "https://nubilefilms.com/video/watch/7TReA9V"
Which can't be found so xpath can't work (can't find the element) and so it breaks.
Using: Nubile Films - 98718 which is the sceneID we have the right request...
INFO (logkit:16) - Requesting GET "https://nubilefilms.com/video/watch/98718"

As i saw the file the original creator used PAutils.Encode for the sceneID when the title is being used at line 14 but never used PAutils.Decode at line 44. Doing this fixed the problem.
`sceneURL = PAsearchSites.getSearchBaseURL(siteID) + '/video/watch/' + PAutils.Decode(metadata_id[0])`
